spring.application.name=football
spring.datasource.url=jdbc:postgresql://localhost:5432/football
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=PostgreSQL17
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
